# GET https://superheroapi.com/api/4491688614216084/466

# GET https://jsonplaceholder.typicode.com/posts

# GET https://www.superheroapi.com/api.php/4491688614216084/search/super

# GET https://www.superheroapi.com/api.php/4491688614216084/search/${searchText}